# Generated by Django 5.2.1 on 2025-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('user', 'Regular User')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpageaccess',
            name='access_level',
            field=models.CharField(choices=[('all', 'all'), ('create', 'create'), ('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
