# Generated by Django 5.2.1 on 2025-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role_alter_userpageaccess_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpageaccess',
            name='access_level',
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
